/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.mrlee.gradle.chungus

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'chungus.greeting' plugin.
 */
class ChungusPluginFunctionalTest {
    @Test fun `fetches yaml`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id("dev.mrlee.gradle.chungus")
                id("org.openapi.generator") version "4.3.0"
            }
            
            chungus {
                services {
                    petstore {
                        url = "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml"
                        format = "yaml"
                    }
                }
            }
        """)

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("generateOpenApiClients")
        runner.withProjectDir(projectDir)

        runner.build()

        assertTrue(projectDir.resolve("build/chungus/openapi/petstore.yaml").exists())
    }
}
