/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package chungus

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'chungus.greeting' plugin.
 */
class ChungusPluginFunctionalTest {
    @Test fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('dev.mrlee.gradle.chungus')
            }
        """)

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("buildCache", "openApiFetch")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        // Verify the result
        assertTrue(projectDir.resolve("build/chungus/openapi/test.json").exists())
    }
}
